import type { Metadata } from "next";
import { Noticia_Text, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

import { AuthModal } from "@/components/modals/auth/AuthModal";
import { TanstackProvider } from "@/components/providers/tanstackprovider";
import { ThemeProvider } from "@/components/providers/themes-provider";

const noticaText = Noticia_Text({
  variable: "--font-notica",
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning className="!scroll-smooth">
      <body
        className={`${noticaText.variable} ${poppins.variable} scrollbar scrollbar-none`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <AuthModal />
          <TanstackProvider>
            <div className="font-notica">
              <div className="font-notica min-h-screen">{children}</div>
            </div>
          </TanstackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
